---
build_from:
  amd64: "ghcr.io/hassio-addons/ubuntu-base/amd64:10.0.10"
  aarch64: "ghcr.io/hassio-addons/ubuntu-base:10.0.10"
  armhf: "ghcr.io/hassio-addons/ubuntu-base:10.0.10"
  armv7: "ghcr.io/hassio-addons/ubuntu-base:10.0.10"
  i386: "ghcr.io/hassio-addons/ubuntu-base:10.0.10"
codenotary:
  base_image: tdlj@tdlj.net
  signer: tdlj@tdlj.net
