name: Build and push container on new Predbat release

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

concurrency:
  group: predbat-${{ github.ref }}
  cancel-in-progress: false

jobs:
  check-and-update:
    name: Check Predbat release
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.decide.outputs.should_build }}
      predbat_version: ${{ steps.get_latest.outputs.predbat_version }}
    steps:
      - uses: actions/checkout@v4

      - id: get_latest
        run: |
          latest=$(curl -s https://api.github.com/repos/springfall2008/batpred/releases/latest | jq -r .tag_name)
          echo "predbat_version=$latest" >> "$GITHUB_OUTPUT"

      - id: get_current
        run: |
          current=$(cat predbat_version.txt)
          echo "current_version=$current" >> "$GITHUB_OUTPUT"

      - id: decide
        run: |
          if [ "${{ steps.get_latest.outputs.predbat_version }}" != "${{ steps.get_current.outputs.current_version }}" ]; then
            echo "should_build=true" >> "$GITHUB_OUTPUT"
          else
            echo "should_build=false" >> "$GITHUB_OUTPUT"
          fi

  build-amd64:
    name: Build amd64 variant ${{ matrix.variant }}
    needs: [check-and-update]
    if: needs.check-and-update.outputs.should_build == 'true'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        variant: [noble, alpine, slim]
        include:
          - variant: noble
            dockerfile: predbat/Dockerfile.noble
            tag_prefix: ''
          - variant: alpine
            dockerfile: predbat/Dockerfile.alpine
            tag_prefix: 'alpine-'
          - variant: slim
            dockerfile: predbat/Dockerfile.slim
            tag_prefix: 'slim-'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push amd64 image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --file ./${{ matrix.dockerfile }} \
            --build-arg BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ) \
            --build-arg PREDBAT_VERSION=${{ needs.check-and-update.outputs.predbat_version }} \
            --tag ghcr.io/${{ github.repository_owner }}/predbat:${{ matrix.tag_prefix }}${{ needs.check-and-update.outputs.predbat_version }}-amd64 \
            --push \
            ./predbat

  build-arm:
    name: Build arm variants ${{ matrix.variant }}
    needs: [check-and-update]
    if: needs.check-and-update.outputs.should_build == 'true'
    runs-on: ubuntu-22.04-arm
    strategy:
      fail-fast: false
      matrix:
        variant: [noble, alpine, slim]
        include:
          - variant: noble
            dockerfile: predbat/Dockerfile.noble
            tag_prefix: ''
          - variant: alpine
            dockerfile: predbat/Dockerfile.alpine
            tag_prefix: 'alpine-'
          - variant: slim
            dockerfile: predbat/Dockerfile.slim
            tag_prefix: 'slim-'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push arm images
        run: |
          for arch in arm64 arm/v7; do
            docker buildx build \
              --platform linux/$arch \
              --file ./${{ matrix.dockerfile }} \
              --build-arg BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ) \
              --build-arg PREDBAT_VERSION=${{ needs.check-and-update.outputs.predbat_version }} \
              --tag ghcr.io/${{ github.repository_owner }}/predbat:${{ matrix.tag_prefix }}${{ needs.check-and-update.outputs.predbat_version }}-${arch//\//_} \
              --push \
              ./predbat
          done

  manifest:
    name: Create multi-arch manifests
    needs: [build-amd64, build-arm, check-and-update]
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create and push manifests
        run: |
          for variant in "" "alpine-" "slim-"; do
            refs=()
            for arch in amd64 arm64 arm_v7; do
              digest=$(docker buildx imagetools inspect ghcr.io/${{ github.repository_owner }}/predbat:${variant}${{ needs.check-and-update.outputs.predbat_version }}-$arch --format '{{ (index .Manifest.Manifests 0).Digest }}')
              refs+=(ghcr.io/${{ github.repository_owner }}/predbat@${digest})
            done
            docker manifest create ghcr.io/${{ github.repository_owner }}/predbat:${variant}v8.24.2 "${refs[@]}"
            docker manifest push ghcr.io/${{ github.repository_owner }}/predbat:${variant}v8.24.2

            docker manifest createghcr.io/${{ github.repository_owner }}/predbat:${variant}latest "${refs[@]}"
            docker manifest push ghcr.io/${{ github.repository_owner }}/predbat:${variant}latest
          done
  release:
    name: Create GitHub Release
    needs: [check-and-update, manifest]
    runs-on: ubuntu-latest
    steps:
      - name: Update repo files (version + Helm) and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          new_version="${{ needs.check-and-update.outputs.predbat_version }}"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git fetch origin
          git pull --rebase origin main
          echo "$new_version" > predbat_version.txt
          sed -i "s/appVersion:.*/appVersion: \"${new_version}\"/" charts/predbat/Chart.yaml
          git add predbat_version.txt charts/predbat/Chart.yaml
          git commit -m "AUTOMATION: Update Predbat references to ${new_version}" || echo "No changes to commit"
          git push origin HEAD
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.check-and-update.outputs.predbat_version }}
          name: "🦇 Predbat Container Build for ${{ needs.check-and-update.outputs.predbat_version }}"
          body: |
            Automated build triggered by new upstream Predbat release ${{ needs.check-and-update.outputs.predbat_version }}.

            Pull images:
            - ghcr.io/${{ github.repository_owner }}/predbat:${{ needs.check-and-update.outputs.predbat_version }}
            - ghcr.io/${{ github.repository_owner }}/predbat:latest
            - ghcr.io/${{ github.repository_owner }}/predbat:alpine-${{ needs.check-and-update.outputs.predbat_version }}
            - ghcr.io/${{ github.repository_owner }}/predbat:alpine-latest
            - ghcr.io/${{ github.repository_owner }}/predbat:slim-${{ needs.check-and-update.outputs.predbat_version }}
            - ghcr.io/${{ github.repository_owner }}/predbat:slim-latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
