name: Build and push container on new Predbat release

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

permissions:
  contents: write
  packages: write

concurrency:
  group: predbat-${{ github.ref }}
  cancel-in-progress: false

jobs:
  check-and-update:
    name: Check Predbat release
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.decide.outputs.should_build }}
      predbat_version: ${{ steps.get_latest.outputs.predbat_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get latest Predbat release tag
        id: get_latest
        run: |
          latest=$(curl -s https://api.github.com/repos/springfall2008/batpred/releases/latest | jq -r .tag_name)
          echo "Latest predbat release: $latest"
          echo "predbat_version=$latest" >> "$GITHUB_OUTPUT"

      - name: Read current version
        id: get_current
        run: |
          current=$(cat predbat_version.txt)
          echo "current_version=$current" >> "$GITHUB_OUTPUT"

      - name: Decide whether to build
        id: decide
        run: |
          if [ "${{ steps.get_latest.outputs.predbat_version }}" != "${{ steps.get_current.outputs.current_version }}" ]; then
            echo "should_build=true" >> "$GITHUB_OUTPUT"
          else
            echo "should_build=false" >> "$GITHUB_OUTPUT"
          fi

  build:
    name: Build ${{ matrix.variant }} on ${{ matrix.os }} for ${{ matrix.arch }}
    needs: [check-and-update]
    if: needs.check-and-update.outputs.should_build == 'true'
    runs-on: ${{ matrix.os }} 
    strategy:
      fail-fast: false
      matrix:
        variant: [noble, alpine, slim]
        arch: [amd64, arm64, v7]
        include:
          - arch: amd64
            os: ubuntu-latest
            platform: linux/amd64
            qemu: false
          - arch: arm64
            os: ubuntu-22.04-arm
            platform: linux/arm64
            qemu: false
          - arch: v7
            os: ubuntu-22.04-arm
            platform: linux/arm/v7
            qemu: true

    env:
      REGISTRY: ghcr.io
      IMAGE: ${{ github.repository_owner }}/predbat
      PREDBAT_VERSION: ${{ needs.check-and-update.outputs.predbat_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Build container
        id: build
        uses: docker/build-push-action@v6
        with:
          context: ./predbat
          file: ./${{ steps.meta.outputs.dockerfile }}
          platforms: ${{ matrix.platform }}
          push: true
          provenance: false
          build-args: |
            BUILD_DATE=${{ github.event.repository.pushed_at || '1970-01-01T00:00:00Z' }}
            PREDBAT_VERSION=${{ env.PREDBAT_VERSION }}
          tags: |
            ghcr.io/${{ env.IMAGE }}:${{ steps.meta.outputs.tag_prefix }}${{ env.PREDBAT_VERSION }}-${{ matrix.arch }}
          cache-from: |
            type=gha
            type=registry,ref=ghcr.io/${{ env.IMAGE }}:cache-${{ matrix.variant }}-${{ matrix.arch }}
          cache-to: |
            type=gha,mode=max
            type=registry,ref=ghcr.io/${{ env.IMAGE }}:cache-${{ matrix.variant }}-${{ matrix.arch }},mode=max,image-manifest=true

  manifest:
    name: Create multi-arch manifests
    needs: [check-and-update, build]
    if: needs.check-and-update.outputs.should_build == 'true'
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE: ${{ github.repository_owner }}/predbat
      PREDBAT_VERSION: ${{ needs.check-and-update.outputs.predbat_version }}
    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifests for each variant
        shell: bash
        run: |
          set -euo pipefail

          create_manifest () {
            local prefix="$1"    # "", "alpine-", or "slim-"
            refs=()
            refs+=( "${REGISTRY}/${IMAGE}:${prefix}${PREDBAT_VERSION}-amd64" )
            refs+=( "${REGISTRY}/${IMAGE}:${prefix}${PREDBAT_VERSION}-arm64" )
            refs+=( "${REGISTRY}/${IMAGE}:${prefix}${PREDBAT_VERSION}-v7" )

            docker manifest create ${REGISTRY}/${IMAGE}:${prefix}${PREDBAT_VERSION} "${refs[@]/#/--amend }"
            docker manifest push   ${REGISTRY}/${IMAGE}:${prefix}${PREDBAT_VERSION}

            # Roll "latest" tags for convenience
            if [ -z "$prefix" ]; then
              docker manifest create ${REGISTRY}/${IMAGE}:latest "${refs[@]/#/--amend }"
              docker manifest push   ${REGISTRY}/${IMAGE}:latest
            else
              docker manifest create ${REGISTRY}/${IMAGE}:${prefix}latest "${refs[@]/#/--amend }"
              docker manifest push   ${REGISTRY}/${IMAGE}:${prefix}latest
            fi
          }

          create_manifest ""
          create_manifest "alpine-"
          create_manifest "slim-"

  release:
    name: Create GitHub Release
    needs: [check-and-update, manifest]
    if: needs.check-and-update.outputs.should_build == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Update repo files (version + Helm) and push
        if: needs.check-and-update.outputs.predbat_version == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          new_version="${{ needs.check-and-update.outputs.predbat_version }}"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git fetch origin
          git pull --rebase origin main
          echo "$new_version" > predbat_version.txt
          sed -i "s/appVersion:.*/appVersion: \"${new_version}\"/" charts/predbat/Chart.yaml
          git add predbat_version.txt charts/predbat/Chart.yaml
          git commit -m "AUTOMATION: Update Predbat references to ${new_version}" || echo "No changes to commit"
          git push origin HEAD

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.check-and-update.outputs.predbat_version }}
          name: "🦇 Predbat Container Build for ${{ needs.check-and-update.outputs.predbat_version }}"
          body: |
            Automated build triggered by new upstream Predbat release ${{ needs.check-and-update.outputs.predbat_version }}.

            Pull images:
            - ghcr.io/${{ github.repository_owner }}/predbat:${{ needs.check-and-update.outputs.predbat_version }}
            - ghcr.io/${{ github.repository_owner }}/predbat:latest
            - ghcr.io/${{ github.repository_owner }}/predbat:alpine-${{ needs.check-and-update.outputs.predbat_version }}
            - ghcr.io/${{ github.repository_owner }}/predbat:alpine-latest
            - ghcr.io/${{ github.repository_owner }}/predbat:slim-${{ needs.check-and-update.outputs.predbat_version }}
            - ghcr.io/${{ github.repository_owner }}/predbat:slim-latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
